spring:
  application:
    name: yns
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

yns:
  text-select:
    captcha:
      enable: true
      siamese-model-path: model/siamese-model.onnx
      yolo-model-path: model/text-select-yolov8s.onnx
      label-path: model/text-select-label.names
